---
abstract: 'Perl client wrapper for Chinese website douban.com API'
author:
  - woosley.xu
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101310'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Douban
recommends: {}
requires:
  HTTP::Request: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Moose: 0
  Net::OAuth: 0
  Scalar::Util: 0
  Test::More: 0
  XML::Atom: 0.35
resources:
  repository: http://github.com/woosley/Perl-Net-Douban
version: 1.06_1
