---
abstract: 'Perl client wrapper for Chinese website douban.com API'
author:
  - woosley.xu
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Douban
requires:
  HTTP::Request: 0
  HTTP::Request::Common: 0
  JSON::Any: 1.29
  LWP::UserAgent: 0
  Moose: 2.0007
  MooseX::StrictConstructor: 0.16
  MooseX::Traits: 0
  Net::OAuth: 0
  Scalar::Util: 0
  Test::More: 0
resources:
  repository: git://github.com/woosley/Perl-Net-Douban.git
version: 1.12
